# Generated by Django 5.1.6 on 2025-03-15 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0002_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="collagename",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentname", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=20)),
                ("phonenumber", models.IntegerField()),
                ("rollno", models.TextField()),
                ("password", models.CharField(max_length=20)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
