# Generated by Django 5.1.6 on 2025-03-15 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0004_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="is_read",
            new_name="read_status",
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("global", "Global"), ("local", "Local"), ("group", "Group")],
                default="group",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
