# Generated by Django 5.1.6 on 2025-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0005_rename_is_read_message_read_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="college",
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
