# Generated by Django 5.1.6 on 2025-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0006_message_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
