# Generated by Django 5.1.6 on 2025-03-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0007_message_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="college",
        ),
        migrations.AddField(
            model_name="message",
            name="sender_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("group", "Group"), ("private", "Private")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(max_length=50),
        ),
    ]
