# Generated by Django 5.1.6 on 2025-03-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0008_remove_message_college_message_sender_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=255)),
                ("duration", models.IntegerField()),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[("Global", "Global"), ("Local", "Local")],
                        max_length=10,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="course_attachments/"
                    ),
                ),
                (
                    "teachername",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_teacher",
                        to="connect.teachers",
                    ),
                ),
            ],
        ),
    ]
