# Generated by Django 5.1.6 on 2025-03-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0009_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("organizer", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("venue", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Hackathon", "Hackathon"),
                            ("Fest", "Fest"),
                            ("Seminar", "Seminar"),
                            ("Workshop", "Workshop"),
                            ("Webinar", "Webinar"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="event_posters/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teachername",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_teacher_to_course",
                        to="connect.teachers",
                    ),
                ),
            ],
        ),
    ]
