# Generated by Django 5.1.6 on 2025-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0010_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="media/course_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="media/event_posters/"
            ),
        ),
    ]
